### ISSUE TITLE
opened swagger docs, and cychart came up, and threw a NPE

### ISSUE THREAD

**Issue by AdamStuart** [cytoscape/cyChart#17]
java.lang.NullPointerException
	at org.cytoscape.cyChart.internal.charts.oneD.HistogramChartController.getHistogram(HistogramChartController.java:145)
	at org.cytoscape.cyChart.internal.charts.oneD.HistogramChartController.setXParameter(HistogramChartController.java:94)
	at org.cytoscape.cyChart.internal.charts.oneD.HistogramChartController.setXParameter(HistogramChartController.java:112)
	at org.cytoscape.cyChart.internal.charts.oneD.HistogramChartController.initialize(HistogramChartController.java:51)
	at org.cytoscape.cyChart.internal.charts.AbstractChartController.<init>(AbstractChartController.java:108)
	at org.cytoscape.cyChart.internal.charts.oneD.HistogramChartController.<init>(HistogramChartController.java:38)
	at org.cytoscape.cyChart.internal.charts.oneD.AppHistograms.getStackPane(AppHistograms.java:30)
	at org.cytoscape.cyChart.internal.charts.oneD.SwingPanel.initComponents(SwingPanel.java:71)
	at org.cytoscape.cyChart.internal.charts.oneD.SwingPanel.<init>(SwingPanel.java:51)
	at org.cytoscape.cyChart.internal.charts.oneD.HistogramFilterDialog.<init>(HistogramFilterDialog.java:26)

**Comment by AdamStuart** [comment]
never found the cause, but added more comprehensive exception handling and made the symptoms go away
