### ISSUE TITLE
getDataSeries has AIOOB

### ISSUE THREAD

**Issue by AdamStuart** [cytoscape/cyChart#19]
java.lang.IndexOutOfBoundsException: Index: 3970, Size: 3970
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at ...twoD.ScatterChartController.getDataSeries(ScatterChartController.java:82)
	at ...twoD.ScatterChartController.setParameters(ScatterChartController.java:40)
	at ...AbstractChartController.setXParameters(AbstractChartController.java:321)
	at ...AbstractChartController$1.changed(AbstractChartController.java:119)

**Comment by AdamStuart** [comment]
CNR
